Update layer.js
Fix the issue ->  

TypeError: Cannot set property 'pythonRequirements' of undefined
    at ServerlessPythonRequirements.createLayers (/Users/alcaljos/Projects/GMR/gmr-imu-video-synch/node_modules/serverless-python-requirements/lib/layer.js:28:56)
From previous event:

Since the layers object seems to not be initialized.